name: Build docker image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Jar file with Maven
      run: mvn -B package --file pom.xml

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aviyam/kafka-topics-exporter:latest
      
    - name: Publish tag to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: aviyam/kafka-topics-exporter:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
   
